// Regenerates packages/db/src/demoDbData.ts from data/demo.db.
// Run after regenerating data/demo.db locally (see README.md "Updating the public demo").
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, "..");
const dbPath = path.join(repoRoot, "data", "demo.db");
const outPath = path.join(repoRoot, "packages", "db", "src", "demoDbData.ts");

const b64 = fs.readFileSync(dbPath).toString("base64");

const contents = `// AUTO-GENERATED by scripts/encode-demo-db.mjs — do not edit by hand.
// Base64-embedded so the demo database ships reliably inside the Vercel serverless
// function bundle as a real JS module import. Vercel's automatic file-tracing did not
// reliably include the raw .db file even when explicitly declared via next.config.js
// outputFileTracingIncludes (a .json config file worked fine via the same mechanism;
// the .db binary consistently did not, even after committing it directly to the repo).
// A base64 string literal is part of the actual module graph, so bundlers can never
// fail to include it.
export const DEMO_DB_BASE64 = "${b64}";
`;

fs.writeFileSync(outPath, contents);
console.log(`Wrote ${outPath} (${contents.length} bytes) from ${dbPath} (${fs.statSync(dbPath).size} bytes)`);
